/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-14 17:10:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.*;
import java.sql.*;

public final class quizApp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Quiz App</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"quizapp.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" integrity=\"sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lobster&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"Reg.js\">\r\n");
      out.write("	history.forward();\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"disp_time()\" class=\"background\">\r\n");
      out.write("	<form action=\"quizapp\" method=\"post\" id=\"regform\">\r\n");
      out.write("		<div class=\"Header\">\r\n");
      out.write("			<div class=\"quizHead\">\r\n");
      out.write("				<h1 align=\"center\">COMPUTER FUNDAMENTALS</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"timer\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"question\">\r\n");
      out.write("				<div class=\"labelclass\">\r\n");
      out.write("					<label for=\"Q1\">1. Ctrl, Shift and Alt are called _______ keys.</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<br>\r\n");
      out.write("				<div class=\"items\">\r\n");
      out.write("					<input type=\"radio\" name=\"question1\" value=\"A) Modifier\">A)\r\n");
      out.write("					Modifier<br> <input type=\"radio\" name=\"question1\"\r\n");
      out.write("						value=\"B) Function\">B) Function<br> <input\r\n");
      out.write("						type=\"radio\" name=\"question1\" value=\"C) Alphanumeric\">C)\r\n");
      out.write("					Alphanumeric<br> <input type=\"radio\" name=\"question1\"\r\n");
      out.write("						value=\"D) Adjustment\">D) Adjustment<br> <br>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q2\">2. A computer cannot 'boot' if it does not\r\n");
      out.write("					have the _______.</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question2\" value=\"A) Compiler\">A)\r\n");
      out.write("				Compiler<br> <input type=\"radio\" name=\"question2\"\r\n");
      out.write("					value=\"B) Loader\">B) Loader<br> <input type=\"radio\"\r\n");
      out.write("					name=\"question2\" value=\"C) Operating system\">C) Operating\r\n");
      out.write("				system<br> <input type=\"radio\" name=\"question2\"\r\n");
      out.write("					value=\"D) Assembler\">D) Assembler<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q3\"> 3. ________ is the process of dividing the\r\n");
      out.write("					disk into tracks and sectors.</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question3\" value=\"A) Tracking\">A)\r\n");
      out.write("				Tracking<br> <input type=\"radio\" name=\"question3\"\r\n");
      out.write("					value=\"B) Formatting\">B) Formatting<br> <input\r\n");
      out.write("					type=\"radio\" name=\"question3\" value=\"C) Crashing\">C)\r\n");
      out.write("				Crashing<br> <input type=\"radio\" name=\"question3\"\r\n");
      out.write("					value=\"D) Allotting\">D) Allotting<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q4\">4. _______ are attempts by individuals to\r\n");
      out.write("					obtain confidential information from you by falsifying their\r\n");
      out.write("					identity.</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question4\" value=\"A) Phishing trips\">A)\r\n");
      out.write("				Phishing trips<br> <input type=\"radio\" name=\"question4\"\r\n");
      out.write("					value=\"B) Computer viruses\">B) Computer viruses<br> <input\r\n");
      out.write("					type=\"radio\" name=\"question4\" value=\"C) Phishing scams\">C)\r\n");
      out.write("				Phishing scams<br> <input type=\"radio\" name=\"question4\"\r\n");
      out.write("					value=\"D) Spyware scams\">D) Spyware scams<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q5\">5. What command is used to count the total number of lines, words, and characters contained in a file?\r\n");
      out.write("				</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question5\" value=\"A) countw\">\r\n");
      out.write("				A) countw <br> \r\n");
      out.write("				<input type=\"radio\" name=\"question5\" value=\"B) wcount\">\r\n");
      out.write("					B) wcount<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question5\" value=\"C) wc\">\r\n");
      out.write("					C) wc<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question5\" value=\"D) count p\">\r\n");
      out.write("					D) count p<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q6\">6. Frames from one LAN can be transmitted to another LAN via the device\r\n");
      out.write("				</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question6\" value=\"A) Router\">\r\n");
      out.write("				A) Router <br> \r\n");
      out.write("				<input type=\"radio\" name=\"question6\" value=\"B) Bridge\">\r\n");
      out.write("					B) Bridge<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question6\" value=\"C) Repeater\">\r\n");
      out.write("					C) Repeater<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question6\" value=\"D) Modem\">\r\n");
      out.write("					D) Modem<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q7\">7. Which of the following is the 1's complement of 10 ?\r\n");
      out.write("				</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question7\" value=\"A) 01\">\r\n");
      out.write("				A) 01 <br> \r\n");
      out.write("				<input type=\"radio\" name=\"question7\" value=\"B) 110\">\r\n");
      out.write("					B) 110<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question7\" value=\"C) 11\">\r\n");
      out.write("					C) 11<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question7\" value=\"D) 10\">\r\n");
      out.write("					D) 10<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q8\">8. Which part interprets program instructions and initiate control operations ?\r\n");
      out.write("				</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question8\" value=\"A) Input\">\r\n");
      out.write("				A) Input <br> \r\n");
      out.write("				<input type=\"radio\" name=\"question8\" value=\"B) Storage unit\">\r\n");
      out.write("					B) Storage unit<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question8\" value=\"C) Logic unit\">\r\n");
      out.write("					C) Logic unit<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question8\" value=\"D) Control unit\">\r\n");
      out.write("					D) Control unit<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q9\">9. Which access method is used for obtaining a record from a cassette tape ?\r\n");
      out.write("				</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question9\" value=\"A) Direct\">\r\n");
      out.write("				A) Direct <br> \r\n");
      out.write("				<input type=\"radio\" name=\"question9\" value=\"B) Sequential\">\r\n");
      out.write("					B) Sequential<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question9\" value=\"C) Random\">\r\n");
      out.write("					C) Random<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question9\" value=\"D) None of the above\">\r\n");
      out.write("					D) None of the above<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"question\">\r\n");
      out.write("			<div class=\"labelclass\">\r\n");
      out.write("				<label for=\"Q10\">10. With respect to a network interface card, the term 10/100 refers to ?\r\n");
      out.write("				</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("			<div class=\"items\">\r\n");
      out.write("				<input type=\"radio\" name=\"question10\" value=\"A) Protocol speed\">\r\n");
      out.write("				A) Protocol speed <br> \r\n");
      out.write("				<input type=\"radio\" name=\"question10\" value=\"B) A fiber speed\">\r\n");
      out.write("					B) A fiber speed<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question10\" value=\"C) Megabits per seconds\">\r\n");
      out.write("					C) Megabits per seconds<br> \r\n");
      out.write("					<input type=\"radio\" name=\"question10\" value=\"D) Minimum and maximum server speed\">\r\n");
      out.write("					D) Minimum and maximum server speed<br> <br>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"buttonclass\">\r\n");
      out.write("		<button class=\"buttons\" type=\"button\" id=\"prev\" onclick=\"prevnext(-1)\">Previous</button>\r\n");
      out.write("    	<button class=\"buttons\" type=\"button\" id=\"next\" onclick=\"prevnext(1)\">Next</button>\r\n");
      out.write("		<input class=\"buttons\" type=\"submit\" id=\"sub\" onclick=\"SubmitResult()\">\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<script>\r\n");
      out.write("		ctab = 0;\r\n");
      out.write("		showtab(ctab);\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
